# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='nom_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nominations end time'),
        ),
        migrations.AlterField(
            model_name='election',
            name='nom_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nominations start time'),
        ),
        migrations.AlterField(
            model_name='election',
            name='vote_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Voting end time'),
        ),
        migrations.AlterField(
            model_name='election',
            name='vote_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Voting start time'),
        ),
    ]
