# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Election_Portal', '0002_auto_20170928_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('birthdate', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth')),
                ('room', models.IntegerField(default=1)),
                ('emailid', models.EmailField(max_length=254)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election_Portal.Branch')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election_Portal.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election_Portal.Section'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
