# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0003_auto_20170928_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Not Updated', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Not Updated', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
