# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0004_auto_20170928_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Please update your', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Profile', max_length=100),
        ),
    ]
