# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0006_auto_20170928_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
